services:
  database:
    container_name: auth_db
    image: postgres:15-alpine3.18
    restart: always
    volumes:
      - auth_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-auth_api}
  api:
    container_name: auth_api
    image: authapi:1.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      JWT_SECRET_KEY: Enter_your_secure_key_MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEA1XIpaAmDv/XkckupdxMnNYFyeY/E995LkGV7J8ipFIOu3bcK3TOPEUziZnJSCR90ml6T/BLs41zti3j7nuChzwIDAQABAkEAj/hh/3+zc057WbC5TM0JfGik+2PDGuHBHFOm/0205lU0SIpKeGpFgxxblXrFcFDC/DMCXun8FwGzgUvn27+B2QIhAPeFcHoPkwgW1WvhJfC92bfl
      DB_CONNECTION_STRING: Host=database;Username=user;Password=123456;Database=auth_api
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  auth_db:
    # external: true
